
#
# This external dependency pulls MU_BASECORE for the Config feature package CI.
# This should not be pulled when consuming this package as a dependency.
#
{
  "scope": "global",
  "type": "git",
  "name": "FEATURE_CONFIG",
  "var_name": "FEATURE_CONFIG_PATH",
  "source": "https://github.com/microsoft/mu_feature_config.git",
  "version": "87f694b13a75765fe8e0d49b74280d447e4abf38",
  "flags": ["set_build_var"]
}
