
#
# This external dependency pulls MU_BASECORE for the Config feature package CI.
# This should not be pulled when consuming this package as a dependency.
#
{
  "scope": "global",
  "type": "git",
  "name": "FEATURE_CONFIG",
  "var_name": "FEATURE_CONFIG_PATH",
  "source": "https://github.com/microsoft/mu_feature_config.git",
  "version": "94258c3baf5abe80a99f4228cda3b56c2bc6bf2c",
  "flags": ["set_build_var"]
}
